### ISSUE TITLE
Add a PaymentInfo view

### ISSUE THREAD

**Issue by cassidyjames** [elementary/onboarding#2] opened 2018-05-23 22:02 UTC
This will require figuring out how and where to store Stripe info, but assuming we do so, this view should:

- Clearly explain how and when users can pay for things
- Prompt a user to enter their payment info (using the [CardNumberEntry from AppCenter](https://github.com/elementary/appcenter/blob/master/src/Widgets/CardNumberEntry.vala))
- Reassure they are always prompted for payment
- Tell them how they can remove or modify payment info (i.e. from System Settings)

I think ideally we would also:
- Move the payment for the OS from the website to this spot, i.e. prompt for payment for the OS here instead
- Maybe explain pay-what-you want?

**Comment by danirabbit** [comment] 2023-03-30 17:55
Duplicate of #87

**Closed by danirabbit** 2023-03-30 17:55 UTC
Labels: Status: Blocked
