### ISSUE TITLE
Adding an option to enable Flathub with a toggle during Onboarding

### ISSUE THREAD

**Issue by sid3425** [elementary/onboarding#148] opened 2021-11-25 09:01 UTC
### Problem

As elementaryOS is moving to Flatpak for its apps, people might expect the Flathub repository to be enabled by default to get access to more apps. I and many others get that the elementary team does not include Flathub by default for security reasons, but it makes the AppCenter feel empty, and for users new to elementaryOS or Linux on the desktop in general might get an impression that there are simply no apps other than the ones available in the AppCenter by default which can be a bad first impression.

### Proposal

The idea is to add a toggle during the Welcome and Onboarding prompt on the first login to enable 3rd party Flatpak sources like Flathub, similar to how it is in the Fedora 35 Workstation post-install setup to enable RPM Fusion and other repositories. That way, users can have a larger library of apps to access and making things easier, while also placing the AppCenter apps as the curated for elementaryOS. If the user enables the toggle, Flathub will be automatically added, and if not, Flathub apps can still be accessible from the official flathub.org website.

**Comment by danrabbit** [comment] 2021-11-25 16:00
Closing as a duplicate of https://github.com/elementary/appcenter/issues/1748#issuecomment-963424996

**Closed by danrabbit** 2021-11-25 16:00 UTC
